'use client'

import './globals.css'

import { BagIcon } from '@nota/common/components'
/* import type { Metadata } from 'next' */
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { UserIcon } from '@nota/common/components/icons/user.icon'
import logo from '../../public/logo.png'
import { useMenu } from '@nota/common/atoms'

const inter = Inter({ subsets: ['latin'] })

/* export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
} */

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	const { isOpen, open, close } = useMenu()
	return (
		<html lang='es'>
			<body className={inter.className}>
				<header
					className='h-20 w-full overflow-hidden fixed flex justify-between items-center bg-base-white px-4'
					style={{
						boxShadow: '0 2px 20px 0 #06002228',
					}}>
					<nav className='hidden bg-base-black'>
						<ul className='hidden justify-between items-center'>
							<li className='font-medium mx-2 cursor-pointer'>COLECCIÓN</li>
							<li className='font-medium mx-2 cursor-pointer'>NEW IN</li>
						</ul>
					</nav>
					<Image src={logo.src} alt='Not available logo' width={160} height={52} />
					<div>
						<ul className='flex justify-between items-center'>
							<li className='mx-2 cursor-pointer hidden md:flex'>
								Ingresar{' '}
								<span className='mx-2'>
									<UserIcon width={20} height={20} />
								</span>
							</li>
							<li className='mx-2 cursor-pointer flex items-center'>
								<p className='hidden md:flex'>Carrito</p>
								<span className='mx-2'>
									<BagIcon width={20} height={20} />
								</span>
							</li>
							<div className='md:hidden'>
								<div
									className='flex flex-col cursor-pointer'
									onClick={() => {
										isOpen ? close() : open()
									}}>
									<div className={`h-1 w-1.5 bg-gray-gray400 rounded-xl ${isOpen ? 'hidden' : 'flex'}`} />
									<div
										className={`h-1 w-4 bg-gray-gray400 rounded-xl my-0.5 transition-all ${
											isOpen ? '-rotate-45 translate-y-1' : 'rotate-0'
										}`}
									/>
									<div
										className={`h-1 bg-gray-gray400 rounded-xl ${
											isOpen ? 'rotate-45 -translate-y-0.5 w-4' : 'rotate-0 w-3'
										}`}
									/>
								</div>
							</div>
						</ul>
					</div>
				</header>
				<div
					className={`w-full sm:w-1/3 h-full  fixed md:hidden top-20 right-0 transition-all  ${
						isOpen ? 'translate-x-0' : 'translate-x-[110%]'
					}`}
					style={{
						boxShadow: '-6px 0px 5px -1.5px #06002228',
					}}>
					<ul className='flex flex-col justify-end items-start sm:items-end px-4 py-8 '>
						<li className='font-medium text-2xl my-2 cursor-pointer'>COLECCIÓN</li>
						<li className='font-medium text-2xl my-2 cursor-pointer'>NEW IN</li>
					</ul>

					<button className='w-full absolute bottom-20 font-light text-lg my-2 cursor-pointer flex items-center justify-center z-10 border-y-2 py-4'>
						Ingresar
						<span className='mx-2'>
							<UserIcon width={20} height={20} />
						</span>
					</button>
				</div>
				<main className='flex min-h-screen flex-col items-center justify-between pt-20 overflow-x-hidden'>
					{children}
				</main>
			</body>
		</html>
	)
}
